### ISSUE TITLE
description not working

### ISSUE THREAD

**Issue by Alkaidcc** [Simon-He95/vscode-common-intellisense#22] opened 2023-08-06 09:28 UTC
<img width="786" alt="image" src="https://github.com/Simon-He95/vscode-common-intellisense/assets/54631354/412dd3bd-5982-4739-b46d-f3011c054445">

**Comment by Simon-He95** [comment] 2023-08-07 12:43
<img width="912" alt="image" src="https://github.com/Simon-He95/vscode-common-intellisense/assets/57086651/ed52870d-bc3a-477a-936a-24fee9ccb984">

It is normal on my side, please try the latest version, if there is still a problem, you can provide a minimal demo that can reproduce

**Comment by Simon-He95** [comment] 2023-08-25 06:41
Due to the lack of a minimal reproducible demo, I will temporarily close this issue

**Closed by Simon-He95** 2023-08-25 06:41 UTC
